export const modulesDetails = [
  {
    title: "Master of JavaScript",
    tutor: "good friends",
    prefix: "all",
    seconds: 0,
    minutes: 0,
    hours: 0,
    percent: 0,
  },
  {
    title: "Fundamentals of JavaScript",
    tutor: "Adam",
    prefix: "[1",
    seconds: 0,
    minutes: 0,
    hours: 0,
    percent: 0,
  },
  {
    title: "Web Browser Environment",
    tutor: "Przemek",
    prefix: "[2",
    seconds: 0,
    minutes: 0,
    hours: 0,
    percent: 0,
  },
  {
    title: "In the world of Frameworks",
    tutor: "Marcin",
    prefix: "[3",
    seconds: 0,
    minutes: 0,
    hours: 0,
    percent: 0,
  },
];
